// server/controllers/documentationController.js
const Documentation = require("../models/Documentation");
const fs            = require("fs");
const { generateWithGemini } = require("../config/aiConfig");

// ✅ Fix for Node.js v22 — pdf-parse workaround
let pdfParse;
try {
  const mod = require("pdf-parse");
  pdfParse = mod.default || mod;
} catch (e) {
  console.warn("pdf-parse not available:", e.message);
}

exports.generateDocumentation = async (req, res) => {
  try {
    const { topic } = req.body;
    if (!topic) return res.status(400).json({ success:false, message:"Topic is required" });

    let fileText = "";
    if (req.file) {
      const buffer = fs.readFileSync(req.file.path);
      if (req.file.mimetype === "application/pdf") {
        if (!pdfParse) return res.status(500).json({ success:false, message:"PDF parsing unavailable. Upload TXT instead." });
        const data = await pdfParse(buffer);
        fileText = data.text;
      } else {
        fileText = buffer.toString("utf-8");
      }
      fs.unlinkSync(req.file.path);
    }

    // ✅ Rich structured prompt for beautiful markdown output
    const prompt = `
You are a professional technical documentation writer.
Generate comprehensive, beautifully formatted documentation for: **${topic}**

${fileText ? `Use this reference content:\n---\n${fileText.slice(0, 4000)}\n---\n` : ""}

Follow this EXACT structure using proper Markdown:

# ${topic}

## 📌 Overview
A clear 2-3 sentence introduction explaining what ${topic} is and why it matters.

## 📖 Definition
A precise, concise definition in 1-2 sentences.

## 🔑 Key Concepts
List and explain each key concept with sub-bullets where needed:
- **Concept 1**: explanation
- **Concept 2**: explanation
- **Concept 3**: explanation

## ⚙️ How It Works
Step-by-step explanation of the mechanism or process. Use numbered steps:
1. Step one
2. Step two
3. Step three

## 💻 Code Example
Provide a complete, working JavaScript code example with comments:

\`\`\`javascript
// Complete working example for ${topic}
// Add inline comments explaining each part
\`\`\`

## 📊 Complexity Analysis (if applicable)
| Operation | Time Complexity | Space Complexity |
|-----------|----------------|-----------------|
| Example   | O(n)           | O(1)            |

## ✅ Advantages
- Advantage 1
- Advantage 2
- Advantage 3

## ❌ Disadvantages / Limitations
- Limitation 1
- Limitation 2

## 🚀 Real-World Applications
1. **Application 1** — brief description
2. **Application 2** — brief description
3. **Application 3** — brief description

## 🔗 Related Topics
- Related concept 1
- Related concept 2
- Related concept 3

## 📝 Summary
A concise 3-4 sentence summary wrapping up the key takeaways.

---
*Generated by VAI — AI Learning Platform*

IMPORTANT RULES:
- Use proper markdown: ##, ###, **, \`code\`, \`\`\`blocks\`\`\`, tables, lists
- Every section must have content — no empty sections
- Code must be complete and runnable
- Keep explanations clear and beginner-friendly
- Use emojis in headings for visual appeal
`;

    const text = await generateWithGemini(prompt);

    const doc = await Documentation.create({
      title:   topic,
      content: text,
      summary: `AI-generated documentation for ${topic}`,
    });

    res.json({ success:true, content:text, data:doc });

  } catch (error) {
    console.error("❌ ERROR:", error);
    if (error.status === 429) return res.status(429).json({ success:false, message:"AI quota exceeded. Try again later." });
    if (error.status === 401) return res.status(401).json({ success:false, message:"Invalid API key." });
    res.status(500).json({ success:false, message:error.message });
  }
};

exports.getDocumentation = async (req, res) => {
  try {
    const docs = await Documentation.find().sort({ createdAt:-1 });
    res.status(200).json({ success:true, count:docs.length, data:docs });
  } catch (error) {
    res.status(500).json({ success:false, message:"Failed to fetch documentation", error:error.message });
  }
};