const Documentation = require("../models/Documentation");
const fs            = require("fs");
const { generateWithGemini } = require("../config/aiConfig");
const { saveEvent } = require("./HistoryController");
const jwt           = require("jsonwebtoken");

let pdfParse;
try {
  const mod = require("pdf-parse");
  pdfParse = mod.default || mod;
} catch (e) { console.warn("pdf-parse not available:", e.message); }

const getUserId = (req) => {
  try {
    const token = req.headers.authorization?.split(" ")[1];
    return token ? jwt.verify(token, process.env.JWT_SECRET).id : null;
  } catch { return null; }
};

const detectCategory = (topic) => {
  const t = topic.toLowerCase();
  const programming = ["javascript","python","java","c++","c#","react","node","express","mongodb","sql","algorithm","data structure","binary","tree","graph","array","linked list","stack","queue","sorting","searching","dynamic programming","recursion","oop","api","rest","graphql","css","html","typescript","redux","git","docker","kubernetes","linux","os","operating system","compiler","database","neural","machine learning","deep learning","ai","artificial intelligence","blockchain","leetcode","dsa","coding","programming","software"];
  const physics     = ["physics","force","energy","motion","velocity","acceleration","newton","gravity","quantum","electromagnetic","thermodynamics","optics","wave","particle","nuclear","relativity","momentum","friction","pressure","electricity","magnetism"];
  const chemistry   = ["chemistry","atom","molecule","reaction","element","compound","bond","acid","base","ph","organic","inorganic","periodic","electron","proton","neutron","mole","valence","oxidation","reduction","catalyst"];
  const math        = ["mathematics","calculus","algebra","geometry","trigonometry","probability","statistics","matrix","vector","differential","integral","derivative","limit","theorem","proof","prime","number theory","combinatorics"];
  const biology     = ["biology","cell","dna","rna","gene","protein","evolution","organism","photosynthesis","respiration","nervous system","ecosystem","taxonomy","virus","bacteria","enzyme","hormone"];
  const history     = ["history","war","revolution","empire","civilization","ancient","medieval","modern","colonial","independence","political","economy","society","culture","religion","dynasty"];

  if (programming.some(k => t.includes(k))) return "programming";
  if (physics.some(k => t.includes(k)))     return "physics";
  if (chemistry.some(k => t.includes(k)))   return "chemistry";
  if (math.some(k => t.includes(k)))        return "mathematics";
  if (biology.some(k => t.includes(k)))     return "biology";
  if (history.some(k => t.includes(k)))     return "history";
  return "general";
};

const buildPrompt = (topic, category, fileText = "") => {
  const fileContext = fileText ? `\n\nUse this reference content:\n---\n${fileText.slice(0, 4000)}\n---\n` : "";
  return `You are an expert educational content writer.\nGenerate comprehensive documentation for: **${topic}**\n${fileContext}\n\nCreate well-structured documentation with Overview, Key Concepts, How It Works, Examples, Best Practices, and Summary sections.\n\n---\n*Generated by VAI — AI Learning Platform*`;
};

exports.generateDocumentation = async (req, res) => {
  try {
    const { topic } = req.body;
    if (!topic) return res.status(400).json({ success: false, message: "Topic is required" });

    let fileText = "";
    if (req.file) {
      const buffer = fs.readFileSync(req.file.path);
      if (req.file.mimetype === "application/pdf") {
        if (!pdfParse) return res.status(500).json({ success: false, message: "PDF parsing unavailable." });
        const data = await pdfParse(buffer);
        fileText = data.text;
      } else {
        fileText = buffer.toString("utf-8");
      }
      fs.unlinkSync(req.file.path);
    }

    const category = detectCategory(topic);
    const prompt   = buildPrompt(topic, category, fileText);
    const text     = await generateWithGemini(prompt);

    const doc = await Documentation.create({
      title:   topic,
      content: text,
      category,
      summary: `AI-generated ${category} documentation for ${topic}`,
    });

    const userId = getUserId(req);
    if (userId) {
      await saveEvent({
        userId,
        type:       "doc",
        title:      `Doc: ${topic}`,
        detail:     `Generated ${category} documentation for "${topic}"`,
        resourceId: doc._id.toString(),
        meta:       { topic, category, docId: doc._id.toString() },
      });
    }

    res.json({ success: true, content: text, category, data: doc });
  } catch (error) {
    console.error("ERROR:", error);
    const status = error.status || error.code;
    if (status === 503) return res.status(503).json({ success: false, message: "Gemini is overloaded. Please try again in a minute." });
    if (status === 429) return res.status(429).json({ success: false, message: "AI quota exceeded. Try again later." });
    res.status(500).json({ success: false, message: error.message || "Generation failed." });
  }
};

exports.getDocumentation = async (req, res) => {
  try {
    const docs = await Documentation.find().sort({ createdAt: -1 });
    res.status(200).json({ success: true, count: docs.length, data: docs });
  } catch (error) {
    res.status(500).json({ success: false, message: "Failed to fetch documentation" });
  }
};

exports.getDocumentationById = async (req, res) => {
  try {
    const doc = await Documentation.findById(req.params.id);
    if (!doc) return res.status(404).json({ success: false, message: "Not found" });
    res.json({ success: true, data: doc });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

exports.getDocumentationByTopic = async (req, res) => {
  try {
    const topic = decodeURIComponent(req.params.topic);
    const doc   = await Documentation.findOne(
      { title: { $regex: topic, $options: "i" } }
    ).sort({ createdAt: -1 });
    if (!doc) return res.status(404).json({ success: false, message: "Not found" });
    res.json({ success: true, data: doc });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};